package main.java.view;

import main.java.controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * LoginPage is the first page that the user sees
 * it allows the user to enter their username and password to access
 * their personal account for the Board Game Library, it also provides
 * a button to go to the registration page (RegisterPage).
 *
 * LoginPage's Layout is generated by LoginPage.form, which sets the
 * content pane of the frame.
 */

public class LoginPage {
    private JPanel loginPanel; // holds all the main login elements
    private JLabel welcomeLabel; // displays a welcome message
    private JTextField usernameField; // where the user can enter their username
    private JPasswordField passwordField1;  // where the user can enter their password
    private JButton logInButton; //submit button for login
    private JButton registerButton; // navigational button to registration page
    private JFrame frame; // holds and displays the main login panel

    public LoginPage() {
        /**
         * void ActionPerformed(ActionEvent e): returns void
         * when the login button is clicked (and released), the system checks if
         * the information is valid for an existing Board Game Library account
         * and either opens the Home Page or shows an error message
         */
        logInButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = usernameField.getText();
                String password = new String(passwordField1.getPassword());
                if (Controller.getInstance().login(username, password)) {
                    JOptionPane.showMessageDialog(null, "Login Successful.");
                    frame.setVisible(false);
                    new HomePageFrame();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Incorrect Username or Password.");
                }
            }
        });
        registerButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                frame.setVisible(false);
                RegisterPage register = new RegisterPage();
                frame.dispose();
            }
        });

        frame = new JFrame("Login");
        frame.setLocationRelativeTo(null);
        frame.setContentPane(loginPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setPreferredSize(new Dimension(300,300));
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        LoginPage page = new LoginPage();
    }
}
