package main.java.view;

import main.java.controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * RegisterPage allows the user to register for a Board Game Library
 * account by providing a name, a username, and a password. If the registration
 * is successful, as in the user information doesn't already exist in the system,
 * then the LoginPage will open and the user will be able to log into their account.
 * If the user already has an account, there is a button to navigate directly to the
 * LoginPage.
 *
 * RegisterPage's Layout is generated by RegisterPage.form, which sets the
 * content pane of the frame.
 */

public class RegisterPage {
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JButton submitButton;
    private JButton goToLogInButton;
    private JTextField nameField;
    private JPanel registerPanel;
    private JFrame frame;


public RegisterPage() {
    submitButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String name = nameField.getText();
            String username = usernameField.getText();
            String password = new String(passwordField.getPassword());
            if (Controller.getInstance().register(username, password, name)) {
                JOptionPane.showMessageDialog(null, "Registration Successful. Please log in.");
                frame.setVisible(false);
                LoginPage login = new LoginPage();
                frame.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Registration Failed.");
        }

    });
    frame = new JFrame("Register");
    frame.setContentPane(registerPanel);
    frame.setPreferredSize(new Dimension(300,300));
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    goToLogInButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            frame.setVisible(false);
            LoginPage login = new LoginPage();
        }
    });
}
}

