package main.java.view;

import main.java.controller.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * RegisterPage allows the user to register for a Board Game Library
 * account by providing a name, a username, and a password. If the registration
 * is successful, as in the user information doesn't already exist in the system,
 * then the LoginPage will open and the user will be able to log into their account.
 * If the user already has an account, there is a button to navigate directly to the
 * LoginPage.
 *
 * RegisterPage's Layout is generated by RegisterPage.form, which sets the
 * content pane of the frame.
 */

public class RegisterPage {
    private JPanel registerPanel; // holds the register elements
    private JTextField nameField; // where the user can enter a name
    private JTextField usernameField; // where the user can enter a username
    private JPasswordField passwordField; // where the user can enter a password
    private JButton submitButton; // submit button for registration
    private JButton goToLogInButton; // opens log in page
    private JFrame frame; // holds and displays the register panel

    /**
     * constructs the register page
     */
    public RegisterPage() {
    /**
     * when the submit button is clicked, the system gets the name, username, and password
     * and attempts to register an account with that information. If the username already
     * exists, the registration will fail and an error message will display.
     */
    submitButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String name = nameField.getText();
            String username = usernameField.getText();
            String password = new String(passwordField.getPassword());
            if (Controller.getInstance().register(username, password, name)) {
                JOptionPane.showMessageDialog(null, "Registration Successful. Please log in.");
                frame.setVisible(false);
                new LoginPage();
                frame.dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Registration Failed.");
        }

    });

    /**
     * new ActionListener() -> actionPerformed(ActionEvent): returns void
     * when the go-to login button is click, the registration page closes and opens
     * an instance of the LoginPage()
     */
    goToLogInButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            frame.setVisible(false);
            new LoginPage();
        }
    });

    frame = new JFrame("Register"); // create the frame
    frame.setContentPane(registerPanel); // set the content of the frame to the Registration GUI form
    frame.setPreferredSize(new Dimension(300,300));
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);

    }
}

